### ISSUE TITLE
May I ask how you solved the dependency problem? 

### ISSUE THREAD

**Issue by loliconRoot** [SamLam140330/ExtraCells2#2]
May I ask how you solved the dependency problem? I tried to build the original version, but Maven failed. I found that your version could be built successfully, but I can't understand how the dependency version number was obtained.
Please forgive me if I disturb you with my meaningless questions.

**Comment by CoolCat467** [comment]
@loliconRoot Look at this commit: https://github.com/SamLam140330/ExtraCells2/commit/d482f7890b3119e7277c81d996f86a463db8271b
